apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant
commonLabels:
  app: home-assistant

resources:
  - pv-hass-config.yaml
  - pvc-hass-config.yaml
  - service.yaml
  - deployment.yaml
  - http-route.yaml

configMapGenerator:
  - name: hass-configuration
    files:
      - configuration.yaml