apiVersion: v1
kind: PersistentVolume
metadata:
  name: hass-config-pv
spec:
  capacity:
    storage: 16Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hass-config-sc
  local:
    path: /disk/etc/home-assistant
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gauss